version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "1337:1337"
    volumes:
      # Mount folder .tmp untuk persistensi database SQLite
      - ./backend/.tmp:/usr/src/app/.tmp
    environment:
      # Variabel lingkungan untuk backend Strapi
      NODE_ENV: production
    restart: always
