version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: "sqlite"
      DATABASE_FILENAME: ".tmp/data.db"
    volumes:
      - ./backend/.tmp:/app/.tmp
